<?php 
echo "<pre>";
$admins = $this->admins;
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
	<table border="1" width="100%">
		<tr>
			<th>User</th>
			<th>Email</th>
			<th>Mobile</th>
			<th>status</th>
			<th>EDIT</th>
			<th>DELETE</th>
		</tr>
		<?php foreach($admins as $row): ?>
		
		<tr>
			<td><?php echo $row->admin_id ?></td>
			<td><?php echo $row->user ?></td>
			<td><?php echo $row->email ?></td>
			<td><?php echo $row->getStatusText() ?></td>
			<td><a href = "<?php echo $this->getUrl('edit','admin',['admin_id'=>$row->admin_id]) ?>">EDIT</a></td>
			<td><a href = "<?php echo $this->getUrl('delete','admin',['admin_id'=>$row->admin_id]) ?>">DELETE</a></td>
		</tr>
	    <?php endforeach; ?>
	
	</table>

</body>
</html>