
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
	<table border="1" width="100%">
		<tr height="100">
			<td colspan="3"><?php $this->getChild('header')->render();?></td>
		</tr>
		<tr height="50">
			<td colspan="3"><?php $this->getChild('message')->render();?></td>
		</tr>
		<tr height="200">
			<td><?php $this->getChild('left')->render();?></td>
			<td><?php echo "<pre>";$this->getChild('contain')->render();?></td>
			<td><?php $this->getChild('right')->render();?></td>
		</tr>
		<tr height="50">
			<td colspan="3">footer</td>
		</tr>
	</table>

</body>
</html>