<?php 
require_once 'view/html/header.phtml';
$customers = $this->getCustomer();
?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
	<form method="POST" action="index.php?c=customer&a=update">
		<table width="50%" border="1">
			<tr bgcolor="pink">
				<td width="30%"><h3>CUSTOMER MANAGE</h3></td>
				<td width="10%" align="center"><button><a href="index.php?c=customer&a=grid">CANCEL</a></button></td>
				<td width="10%" align="center"><button type="submit">SAVE</button></td>
			</tr>
		</table>
		<table width="50%" border="1">
			<?php foreach($customers as $customer) { ?>
			<tr>
				<td>CUSTOMER ID</td>
				<td><input type="text" name="customer[customer_id]" value="<?php echo $customer['customer_id'] ?>"></input></td>
			</tr>
			<tr>
				<td>First Name</td>
				<td><input type="text" name="customer[first_name]" value="<?php echo $customer['first_name'] ?>"></input></td>
			</tr>
			<tr>
				<td>Last Name</td>
				<td><input type="text" name="customer[last_name]" value="<?php echo $customer['last_name'] ?>"></input></td>
			</tr>
			<tr>
				<td>E-Mail</td>
				<td><input type="text" name="customer[email]" value="<?php echo $customer['email'] ?>"></input></td>
			</tr>
			<tr>
				<td>Mobile</td>
				<td><input type="text" name="customer[mobile]" value="<?php echo $customer['mobile'] ?>""></input></td>
			</tr>
			<tr>
				<td>Gender</td>
				<td>
					<select name="customer[gender]">
						<option value="<?php echo $customer['gender'] ?>"></option>
						<option value="MALE">MALE</option>
						<option value="FEMALE">FEMALE</option>
					</select>
				</td>
			</tr>
			<tr>
				<td>status</td>
				<td>
					<select name="customer[status]">
						<option value="AVAILABLE">AVAILABLE</option>
						<option value="INAVAILABLE">INAVAILABLE</option>
					</select>
				</td>
			</tr>
		<?php } ?>
		</table>
	</form>

</body>
</html>