<?php 

require_once 'view/html/header.phtml';
$customers = $this->customers;
?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
	<table width="100%" border="1" >
		<tr bgcolor="pink">
			<td colspan="9"><h3>MANAGE CUSTOMER</h3></td>
			<td colspan="2" align="center"><button><a href="<?php echo $url->getUrl('add','customer') ?>"><h3>ADD</h3></a></button></td>
		</tr>
		<tr>
			<th>CUSTOMER ID</th>
			<th>First Name</th>
			<th>Last Name</th>
			<th>E-Mail</th>
			<th>Mobile</th>
			<th>Gender</th>
			<th>Status</th>
			<th>Address</th>
			<th>City</th>
			<th>EDIT</th>
			<th>DELETE</th>
		</tr>
		<?php foreach($customers as $row) {?>
		<tr>
			<td><?php echo $row->customer_id ?></td>
			<td><?php echo $row->first_name ?></td>
			<td><?php echo $row->last_name ?></td>
			<td><?php echo $row->email ?></td>
			<td><?php echo $row->mobile  ?></td>
			<td><?php echo $row->gender ?></td>
			<td><?php echo $row->status ?></td>
			<td><?php echo $row->address ?></td>
			<td><?php echo $row->city ?></td>
			<td><a href="index.php?c=customer&a=edit&customer_id=<?php echo $customer['customer_id'] ?>">EDIT</a></td>
			<td><a href="index.php?c=customer&a=delete&customer_id=<?php echo $customer['customer_id'] ?>">DELETE</a></td>
		</tr>
	<?php } ?>
	</table>

</body>
</html>