<!DOCTYPE html>
<?php 

require_once 'view/html/header.php';

$categorys = $this->getCategory();

?>

<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>

<body>
	<form method="POST" action="index.php?c=category&a=insert">
    <table width="50%" border="1">
    	<tr>
    		<td width ="30%" bgcolor="pink" ><h3>CATEGORY ADD<h3></td>
    		<td width = "10%"bgcolor="pink" align="center"><a href="index.php?c=category&a=grid"><h3>CANCEL</h3></a></td>
    		<td width="10%" bgcolor="pink" align="center"><button type="submit"><h3>SAVE<h3></button></td>
    	</tr>
    	
    </table>
	<table width="50%" border="1">
		<tr>
			<td>Category Name</td>
			<td><input type="text"></input></td>
		</tr>
		<tr>
			<td>Discription</td>
			<td><input type="text"></input></td>
		</tr>
		<tr>
			<td>Url</td>
			<td><input type="text"></input></td>
		</tr>
		<tr>
			<td>Category</td>
			<td>
					<select name="category">
					<?php foreach($categorys as $category) {?>
						<option value ="<?php echo $category['category_id'] ?>" ><?php echo $category['name'] ?></option>
					<?php }?>
					</select>
			</td>
		</tr>
	</table>
	</form>

</body>
</html>