<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
	<form method="POST" action="index.php?c=salesman&a=insert">
		<table width="50%" border="1">
			<tr bgcolor="pink">
				<td ><h3>ADD SALESMAN</h3></td>
				<td align="center"><a href="index.php?c=salesman&a=grid"><h3>CANCEL</h3></a></td>
				<td align="center"><button type="submit"><h3>SAVE</h3></button></td>
			</tr>
		</table>
		<table width="50%" border="1">
			<tr>
				<td>First Name</td>
				<td><input type="text" name="salesman[first_name]"></input></td>
			</tr>
			<tr>
				<td>Last Name</td>
				<td><input type="text" name="salesman[last_name]"></input></td>
			</tr>
			<tr>
				<td>E-Mail</td>
				<td><input type="text" name="salesman[email]"></input></td>
			</tr>
			<tr>
				<td>Mobile</td>
				<td><input type="text" name="salesman[mobile]"></input></td>
			</tr>
			<tr>
				<td>gender</td>
				<td>
					<select name="status">
						<option value="MALE">MALE</option>
						<option value="FEMALE">FEMALE</option>
					</select>
				</td>
			</tr>
			<tr>
				<td>Status</td>
				<td>
					<select name="status">
						<option value="AVAILABLE">AVAILABLE</option>
						<option value="INAVAILABLE">INAVAILABLE</option>
					</select>
				</td>
			</tr>
			<tr bgcolor="pink">
				<th>SALESMAN INFO</th>
			</tr>
			<tr>
				<td>Adress</td>
				<td><input type="text" name="Address[address]"></input></td>
			</tr>
			<tr>
				<td>City</td>
				<td><input type="text" name="Address[city]"></input></td>
			</tr>
			<tr>
				<td>Zipcode</td>
				<td><input type="text" name="Address[Zipcode]"></input></td>
			</tr>
			<tr>
				<td>Country</td>
				<td><input type="text" name="Address[country]"></input></td>
			</tr>
			<tr>
				<td>State</td>
				<td><input type="text" name="Address[state]"></input></td>
			</tr>
		</table>
	</form>
</body>
</html>